version: "3"

services:

  mosquitto:
    container_name: ${PLATFORM_NAME}_mosquitto
    build: ./images/mosquitto
    networks:
      - internal_net
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto:/mosquitto/config/
      - ${HOST_VOLUMES_PATH}/mosquitto/data:/mosquitto/data/
      - ${HOST_VOLUMES_PATH}/mosquitto/mqtts_certs:/mosquitto/mqtts_certs/
      - ${SSL_CERTIFICATE_CA_PATH}:/mosquitto/wss_certs/iot_platform_ca.pem
      - ${SSL_CERTIFICATE_SERVER_PATH}:/mosquitto/wss_certs/iot_platform_cert.cer
      - ${SSL_CERTIFICATE_KEY_PATH}:/mosquitto/wss_certs/iot_platform.key
    restart: unless-stopped

  nginx_proxy:
    container_name: ${PLATFORM_NAME}_nginx_proxy
    build: ./images/nginx
    networks:
      - internal_net
    ports: 
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: unless-stopped
    volumes:
      - ./images/nginx/static/:/static/
      - ${SSL_CERTIFICATE_CA_PATH}:/etc/ssl/certs/iot_platform_ca.pem
      - ${SSL_CERTIFICATE_SERVER_PATH}:/etc/ssl/certs/iot_platform_cert.cer
      - ${SSL_CERTIFICATE_KEY_PATH}:/etc/ssl/certs/iot_platform.key
      - ${SSL_DHPARAM_PATH}:/etc/ssl/certs/dhparam-2048.pem
    depends_on:
      - nodered

  nodered:
    container_name: ${PLATFORM_NAME}_nodered
    build: ./images/nodered
    user: "${UID}:${GID}"
    networks:
      - internal_net
    env_file:
      - .env
    ports:
      - "127.0.0.1:1880:1880"
    volumes:
      - ${HOST_VOLUMES_PATH}/nodered/:/data
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy   

  postgres:
    container_name: ${PLATFORM_NAME}_postgres
    build:
      context: ./images/postgres
    networks:
      - internal_net  
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      GRAFANA_DB_PASSWORD: ${GRAFANA_DB_PASSWORD}
      GRAFANA_DATASOURCE_PASSWORD: ${GRAFANA_DATASOURCE_PASSWORD}
    volumes:
      - ${HOST_VOLUMES_PATH}/pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 4s
      timeout: 120s
      retries: 30
    restart: unless-stopped

  grafana:
    container_name: ${PLATFORM_NAME}_grafana
    build: ./images/grafana
    user: "${UID}:${GID}"
    networks:
      - internal_net      
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ${HOST_VOLUMES_PATH}/grafana:/var/lib/grafana
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,briangann-gauge-panel,vonage-status-panel,neocat-cal-heatmap-panel
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - HOME_DASHBOARD_PATH=/var/lib/grafana/data/home_dashboard.json
      - GMAIL_USER=${GMAIL_USER}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - TELEGRAM_BOTTOKEN=${TELEGRAM_BOTTOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}
      - GF_RENDERING_SERVER_URL=http://grafana_renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:5000/
      - GF_LOG_FILTERS=rendering:debug
      - POSTGRES_DB=${POSTGRES_DB}
      - GRAFANA_DB_PASSWORD=${GRAFANA_DB_PASSWORD}
      - GRAFANA_DATASOURCE_PASSWORD=${GRAFANA_DATASOURCE_PASSWORD}
      - MAIN_ORGANIZATION_NAME=${MAIN_ORGANIZATION_NAME}
      - MAIN_ORGANIZATION_DATASOURCE_NAME=${MAIN_ORGANIZATION_DATASOURCE_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:5000/api/health || exit 1"]
      interval: 10s
      timeout: 300s
      retries: 30
    depends_on:
      postgres:
        condition: service_healthy     

  pgadmin4:
    container_name: ${PLATFORM_NAME}_pgadmin
    build:
      context: ./images/pgadmin4 
      dockerfile: Dockerfile.rpi4
    user: "${UID}:${GID}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - ${HOST_VOLUMES_PATH}/pgadmin_data/servers.json:/pgadmin4/servers.json
       - ${HOST_VOLUMES_PATH}/pgadmin_data/pgadmin:/var/lib/pgadmin
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost || exit 1"]
      interval: 10s
      timeout: 300s
      retries: 30      
    restart: unless-stopped

  admin_api:
    build:
      context: ./images/admin_api
      dockerfile: Dockerfile 
    container_name: ${PLATFORM_NAME}_admin_api
    networks:
      - internal_net
    restart: always 
    volumes:
      - ${SSL_CERTIFICATE_SERVER_PATH}:/app/ssl_config/iot_platform.cer
      - ${SSL_CERTIFICATE_KEY_PATH}:/app/ssl_config/iot_platform.key
      - ${HOST_VOLUMES_PATH}/mosquitto/mqtts_certs/ca.crt:/app/mqtts_certs/ca.crt
      - ${HOST_VOLUMES_PATH}/mosquitto/mqtts_certs/ca.key:/app/mqtts_certs/ca.key
    working_dir: /app
    env_file:
      - .env
    environment:
      PORT: 3200
      WAIT_HOSTS: postgres:5432, grafana:5000
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure https://localhost:3200/health || exit 1"]
      interval: 10s
      timeout: 300s
      retries: 30
    ports:
    - "3200:3200"
    depends_on:
      grafana:
        condition: service_healthy    

  admin_frontend:
    build: 
      context: ./images/admin_frontend
      dockerfile: Dockerfile
    container_name: ${PLATFORM_NAME}_admin_frontend
    networks:
      - internal_net
    command: nginx -g "daemon off";
    depends_on:   
      admin_api:
        condition: service_started

  mobile_frontend:
    build: 
      context: ./images/mobile_frontend
      dockerfile: Dockerfile
    container_name: ${PLATFORM_NAME}_mobile_frontend
    networks:
      - internal_net
    command: nginx -g "daemon off";
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      admin_api:
        condition: nginx_proxy     
      admin_api:
        condition: service_started
  
  portainer:
    image: portainer/portainer
    container_name: ${PLATFORM_NAME}_portainer
    networks:
      - internal_net
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_VOLUMES_PATH}/portainer_data:/data

networks:
  internal_net:
